[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "autogen>=0.7.6",
    "fix-busted-json>=0.0.18",
    "psutil>=7.0.0",
    "python-dotenv>=1.0.1",
    "streamlit>=1.42.2",
]
